### ISSUE TITLE
i have issue related mongoDB

### ISSUE THREAD

**Issue by getsettalk** [codersgyan/inshare-file-sharing-app-api#13]
this is error display on console :

`` Mongoose is connected
MongooseError: Operation `files.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\expressJsBySujeet\fileShareBackend\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:151:23)

``

**Comment by getsettalk** [comment]
Mongoose is connected
MongooseError: Operation `files.insertOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\expressJsBySujeet\fileShareBackend\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:151:23)
